
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS hero_title TEXT DEFAULT 'Bienvenue au Coin des Apiculteurs 🐝',
  ADD COLUMN IF NOT EXISTS hero_subtitle TEXT DEFAULT 'Ici, on parle ruches, miel et passion',
  ADD COLUMN IF NOT EXISTS hero_cta_text TEXT DEFAULT 'Découvrir les articles',
  ADD COLUMN IF NOT EXISTS instagram_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS facebook_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS youtube_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS twitter_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS tiktok_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS whatsapp_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_hero BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_buzz_section BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_newsletter BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_categories_filter BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_chatbot BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_bee_animations BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS comments_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS comments_moderation BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_author BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_date BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_related_articles BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_share_buttons BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS articles_per_page INTEGER DEFAULT 10,
  ADD COLUMN IF NOT EXISTS maintenance_mode BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS public_registration BOOLEAN DEFAULT false;
